version: '3'

services:
  app:
#    image: node:lts-alpine
    build:
      context: .
      dockerfile: ./Docker/Dockerfile
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    ports:
      - "3000:3000"
    command: "sh ./start.sh"